POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlkIjoiNWQ4ZTQ3YmE0Yjg4OWExOTJjZTQ5ZGIxIiwiaWF0IjoxNTcwMjU0Njc1fQ.fLnSLYLDh3na6fRGCU39Z_26xReboMXfnsVwRDnXEcs

{
  "title": "mainly miles",
  "author": "unknown",
  "url": "mainlymiles.com",
  "likes": "2012"
}